title: Financial Reporting Agent
description: AI-powered insights with Microsoft Fabric + Vanna AI
theme: just-the-docs

# Enable documentation navigation
collections:
  docs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      navigation: docs

# Optional: GitHub repo link
repository: wbgreen0405/Financial-Reporting-Agent
